### ISSUE TITLE
aarch64 builds?

### ISSUE THREAD

**Issue by poetaster** [rec0de/pixl#1]
Any chance of you uploading them to store? I can help push them into chum on the build server which would at least allow people to install from chum?

**Comment by rec0de** [comment]
Oh boy, it's been a while since I've worked with Sailfish — for starters, what is chum?  

But yeah, I think I should be able to get aarch64 to work somehow, give me a couple days maybe

**Comment by poetaster** [comment]
Chum is a community effort to get everything on sailfishes build system. One of my packages: https://build.sailfishos.org/package/show/sailfishos:chum:testing/harbour-moremahjong

Eases supporting builds and will hopefully be a pipeline to build to harbour in the long term. 

I'll try building building pixel and then I'll send you results!

**Comment by poetaster** [comment]
Ah, just looked. The repo structure has reflect the build structure as it is in the SDK more.  For instance a spec file needs to be located in  a directory /rpm
https://github.com/poetaster/harbour-dwd for example.

**Comment by rec0de** [comment]
Wow, a lot has changed since I pushed my last updates... I just reinstalled the SDK and I think I got the builds to work.  
Honestly I don't think it's worth the effort to bring my build infrastructure up to date, so I'll just push the RPMs to the harbour manually.

Anyway, thanks for reaching out! You'll get the long overdue pronoun update ported from Android as a bonus lol

**Comment by rec0de** [comment]
Fixed in aacc2abcb135d17255f4b7658700d60afc734b7c, harbour update is on its way

**Comment by poetaster** [comment]
Thanks, that's great!
